### ISSUE TITLE
IArtist interface missing IReleaseGroup array prop

### ISSUE THREAD

**Issue by jackbilestech** [Borewit/musicbrainz-api#190]
This may be intentional as I'm missing a key functionality to this API, potentially. But the following example below gets rejected by TypeScript.

I'm trying to make as few calls as possible so I feel this is a prettier and simpler way to get the album information of an artist. 

## Example
```js
var {artists}:any =  await mbApi.searchArtist("Oasis") //Get artist
artists.sort( function(a:any, b:any){return a.score + b.score}) //Sort by score
const result = await mbApi.getArtist(artists[0].id, ['release-groups']) //Get albums
console.log(result)
```

## Proposed Fix
```ts
export interface IArtist {
...
"release-groups"?: IReleaseGroup[];
}
```

**Comment by Borewit** [comment]
Can you create a PR for this @jackbilestech?

**Comment by jackbilestech** [comment]
Sure thing @Borewit . Will PR tonight.
