### ISSUE TITLE
Add support for 'browse requests'

### ISSUE THREAD

**Issue by Borewit** [Borewit/musicbrainz-api#2]
Implement "Browse" API REST calls
Ref: 
* https://wiki.musicbrainz.org/Development/JSON_Web_Service#Browse
* https://wiki.musicbrainz.org/MusicBrainz_API#Linked_entities

Example of browse REST request: http://musicbrainz.org/ws/2/release?label=47e718e1-7ee4-460c-b1cc-1192a841c6e5&offset=12&limit=2

**Comment by benthehorn** [comment]
I would really like to be able to get the metadata from a cd by just searching the barcode number. Is that possible ?

**Comment by lufinkey** [comment]
Is this supported? It mentions browse requests in the documentation, but it doesn't look like it's actually supported based on the code and this Issue
