### ISSUE TITLE
Not sure i I understand how to run a query

### ISSUE THREAD

**Issue by GerritKuilder** [Borewit/musicbrainz-api#255]
the sample code:
const query = 'query="We Will Rock You" AND arid:0383dadf-2a4e-4d10-a46a-e9e041da8eb3';
const result = await mbApi.query<mb.IReleaseGroupList>('release-group', {query});

in nodejs I get an error warning that it can only be used in typescript.

and just using 'query' results in it is not a function.
All my other attempts have have failed.

Any suggestions?

And anyone tips on how to deal with the elements with a hyphen in the name?
Regards,

gerrit

**Comment by Borewit** [comment]
Maybe:
```js
 const result = await mbApi.searchReleaseGroup({query: '"We Will Rock You" AND arid:0383dadf-2a4e-4d10-a46a-e9e041da8eb3'});
```
Good luck!
