### ISSUE TITLE
Incompatible with react-scripts 5.0 (and webpack 5.0)

### ISSUE THREAD

**Issue by HarryOMalley** [Borewit/musicbrainz-api#401]
The latest version of react-scripts utilising webpack 5.0 has deprecated the use of polyfills to map core node.js modules.

Example error when implementing basic musicbrainz-api functionality to create-react-app@5.0.0 is attached.
[error.txt](https://github.com/Borewit/musicbrainz-api/files/8054730/error.txt)

Changelog for create-react-app@5.0.0: https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md
Documentation on migrating to support webpack v5: https://webpack.js.org/migrate/5/#preparations

**Comment by HarryOMalley** [comment]
@Borewit perhaps a version using Ky could be considered? Some refactoring to use Fetch parameters would be required, but should be feasible. I will start refactoring to use Ky and report back.

**Comment by HarryOMalley** [comment]
I have tried to modify the code to use Ky and crypto-js, but as soon as I modify the source and attempt to run the tests, it fails with:

`
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/user/musicbrainz-api/test/test-musicbrainz-api.ts
`
I have tried to figure out why it is not working, but cannot figure out why it suddenly starts failing as soon as I modify the code (I am not even modifying the test code). @Borewit not sure if you have any idea about it?

**Comment by HarryOMalley** [comment]
No worries @Borewit! Good catch with the ky-universal, I didn't realise that it was designed with both use cases in mind. I was thinking of two separate implementations, one with got, one with ky, but changing to just use ky-universal is far more sensible. 

> Did you change from CommonJS to ESM?

I did not no, should I be doing that? I only added ky and modified the calls to got to match the ky syntax.

I will try out ky-universal and see how it goes, thanks!

**Comment by Borewit** [comment]
> I didn't realise that it was designed with both use cases in mind.

I wrote the module for a personal Node.js project, but I tried to keep compatibly with browsers. 

> I did not no, should I be doing that? 

Please don't. But if you believe ESM is the best solution for a hybrid Webpack 5 complaint module, let me prepare that transition in a dedicated PR / parallel branch. I have done it for some other modules, so I am reasonable familiar with that transition. Devil is in detail with that transition, unit test will break, probable good to move from deprecated tslint to eslint, etc.

**Comment by HarryOMalley** [comment]
Ah gotcha. I have decided to use an express back end service anyway, so I don't need this to be browser compliant any more - great work on the module it works excellently! :)
