### ISSUE TITLE
Missing Types for "Genre" & "Tag"

### ISSUE THREAD

**Issue by Haschikeks** [Borewit/musicbrainz-api#504]
Hi 👋 

I'm back with more types :)

I also noticed that there are currently no types for things like "Genre" or "Tag" and their respective connection to lookup.
Making this generic might be a bit harder, because for the standard lookups it depends on the `inc` parameters.

One easy approach where to just add the missing interfaces/types and tell the user to just define the needed types them selfs.

```typescript
// musicbrainz.types.ts
interface ITag {
  id: string;
  name: string;
}

interface IGenre {
  id: string;
  name: string;
  count: number;
  disambiguation: string;
}
```

```typescript
// index.ts
import { IArtist, ITag } from "musicbrainzapi";

type ArtitstWithTags = IArtist & { tags?: ITag[] }

type ArtistWithGenreTags = IArtist & { tags?: ITag[], genres?: IGenre[] }
```

In a second iteration someone could look into doing it in a more generic way and provide the correct type from the lookup method itself.

**Comment by Borewit** [comment]
Related to support all API features, please also note that a number of changes are still pending in #405.

Some functions are only there, just to distinct the return type. It's a balance between generic functionality and typed return types. It is not possible to have a type dependency in the return based on a method input argument, is it?

**Comment by Haschikeks** [comment]
I see.

> Some functions are only there, just to distinct the return type

You mean e.g `lookupArtist`?
I like having those "extra" functions, as they make it more intuitive to get what you’re looking for.

> It is not possible to have a type dependency in the return based on a method input argument, is it?

I think it is possible. [prisma](https://github.com/prisma/prisma) is doing that with their queries. If you define includes as parameter, the return type knows about them.
```typescript
const artist = await prisma.artist.findFirst({
  include: {
    genres: true,
  }
})
```
Then `artist` has the following type, without the need to type it manually .
```typescript
const artist: (Artist & {genres: Genre[]}) | null;
```
But I haven't looked into, how they do it.

If I can help, point me in the direction and I can see what I can do.

**Comment by Borewit** [comment]
The point of the module is to provide easy API access to MusicBrainz. 

I have to many things on my plate at the moment. Would you be interested sharing ownership of this project?

**Comment by Borewit** [comment]
If you can help to finalize #405, that would be nice. If you believe it can be done better type-wise, be my guest. Intuitive, I like that. This about providing easy access to JavaScript to MusicBrainz API isn't?

**Comment by Haschikeks** [comment]
> The point of the module is to provide easy API access to MusicBrainz.

Yes, I agree with that.

>Would you be interested sharing ownership of this project @[Haschikeks](https://github.com/Haschikeks)?

I need to think about that.

I would non the less look into helping to finalize #3 & #405. It seems that some of the things in the PR are already merged, like the `lookup` functions?

**Comment by Borewit** [comment]
Are you willing to implement this one @Haschikeks ?

**Comment by Haschikeks** [comment]
Hey

I can definitely have another look at it.

I think I can provide better feedback at the end of the week.

**Comment by Haschikeks** [comment]
Okay, so after experimenting a little bit we would need to do something like this

```typescript
export interface ReleaseIncludes {
  labels: ILabel;
  recordings: IRecording;
}
```
and use it in the lookup functions like this:
```typescript
public lookupRelease<T extends (keyof mb.RInc)[]>(releaseId: string, inc: T) {
  return this.lookupEntity<mb.IRelease & { [K in T[number]]: mb.RInc[K] }, keyof mb.RInc>('release', releaseId, inc);
}

const r = await this.lookupRelease("", ["labels"]);
const title = r.title;
const labels = r.labels.name;
// This throws an error
const recordings = r.recordings;
```

**Comment by Borewit** [comment]
@Haschikeks, you gave me some inspiration: #823

Can you combine your work with that?

**Comment by Haschikeks** [comment]
I'll check if this would work too.

May I ask why you want to get rid of the various `lookup` functions?

**Comment by Haschikeks** [comment]
If we wanted to use the above outlined type system we can do that.
But  there would need to be some changes to your outline.

To use the include based typing it probably would look something like this:
```typescript
  public lookupEntity(entity: 'release', mbid: string): Promise<mb.IRelease>;
  public lookupEntity<T extends (keyof mb.ReleaseIncludes)[]>(entity: 'release', mbid: string, inc?: T): Promise<mb.IRelease & { [K in T[number]]: mb.ReleaseIncludes[K] }>;
``` 
The line without the `inc` parameter is needed to avoid typing problems with the output. And on the other `lookupEntity` line we use the generic type as a shortener for later uses.

**Comment by Borewit** [comment]
> The line without the inc parameter is needed to avoid typing problems with the output.

Which typing problems with the output?
I tried to remove it, but then I get typing problems passing the `inc` parameter.

```ts
public lookupEntity(entity: 'release', mbid: string, inc?: IReleaseIncludeOptions): Promise<mb.IRelease>;
public lookupEntity<T extends (keyof mb.ReleaseIncludes)[]>(entity: 'release', mbid: string, inc?: T): Promise<mb.IRelease & { [K in T[number]]: mb.ReleaseIncludes[K] }>;
```

I think actually to type the `inc` more strict, is more interesting then adapting the output typing based in the `inc`. I believe that is what you try to do, please correct me if I am misunderstood.

We can define the output interface with all the possible inclusions. We cannot guarantee that all information is present anyway. Also it is important to keep the return type simple, so users do not have to declare a very complex type, if declare the output type in their code. Then we trade one problem for another.

**Comment by Haschikeks** [comment]
> I tried to remove it, but then I get typing problems passing the `inc` parameter.

That's interesting.



> I think actually to type the `inc` more strict, is more interesting then adapting the output typing based in the `inc`. I believe that is what you try to do, please correct me if I am misunderstood.

Yes, I defnitly aimed for a strict `inc` type. But we already had that with the String Unions like `ReleasesIncludes`.

> We can simply define the output interface with all the possible inclusions. We cannot guarantee that all information is present anyway. Also it is important to keep the return type simple, so users do not have to declare a very complex type

If  some of the includes are not always present, we can add `undefined` to the output typing. And in regards to user typing the result it probably would look something like this, which I find acceptable:
```typescript
    const r: mb.IRelease & { labels: mb.ILabel } = await this.lookupEntity("release", "as", ["labels"]);
```

If you want I can prepare a full pull request to see it all and not just bits and pieces.
