### ISSUE TITLE
README examples not up to date

### ISSUE THREAD

**Issue by richsoni** [Borewit/musicbrainz-api#567]
I was having trouble getting the examples to work in the README, but after digging into the source code I figured out they were using an old version of the library:

For example:
```js
  const artist = await mbApi.lookupEntity('artist', {query: 'ab2528d9-719f-4261-8098-21849222a0f2'});
```

Should be:
```js
  const artist = await mbApi.lookupEntity('artist', 'ab2528d9-719f-4261-8098-21849222a0f2');
```

**Comment by Haschikeks** [comment]
Hi @richsoni

thank you for reporting.
I've created a Pull request to update/fix the examples.

**Comment by richsoni** [comment]
thanks!!!
