### ISSUE TITLE
Promise stuck on pending

### ISSUE THREAD

**Issue by turobiter** [Borewit/musicbrainz-api#670]
Using the documentation provided to create an app in node js. Setting up the api the terminal keeps returning promise {pending}.

I'm unsure how to resolve this. Since I'm not making calls to a URL I can't figure out how to get info and log it to the console. 

I have this: 
`const mbg = new MusicBrainzApi({
  appName: 'appname',
  appVersion: '1.2',
  appContactInfo: 'site.com'
})`

which logs to the console the promise pending issue. I can't complete and db searches until obviously I can fulfill the promise. How do I do this?

(I am fairly new to node js, so apologies if this is a dumb q).

**Comment by Borewit** [comment]
Check how to work with promises here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Alternatively you can handle promised with async 2 await https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

One way of looking at promises is that it's a conventional way to handle the traditional success & error callback methods. See also the README for code examples.

I am just equipes with mobile phone at the moment, so limits me to answer your question better at the moment.

**Comment by turobiter** [comment]
Thanks for these links! I think I am understanding a bit more about promises, but I'm still unsure how to apply it to my problem. How do I configure this wrapper and fulfill the promise?

**Comment by Borewit** [comment]
'''js

const artistPromise = mbg.lookupEntity('artist', 'ab2528d9-719f-4261-8098-21849222a0f2').then(successCallback, failureCallback);

artistPromise.then(artist => {
  console.log(artist);
})
'''

So a promise returned immediately. At that moment the result (artist) is not available yet. In the background the artist is being fetched. When the artist is available, the success / resolve handler has passed via 'then' is called with the result, artist.

**Comment by turobiter** [comment]
Alright, this is starting to make a lot more sense. I do have a couple more questions which I hope you'll be able to help me with!

1. Why do I need a second .then-- the way I've defined successCallback, should that not return the result?
2. How do I return a specific value of a key in the result? For example, in the function we are currently looking up, I want to log the gender of the artist. I thought artistPromise.gender...or artist.gender (?) should give me this, but neither do. 
3. Do I have to do this .then chaining for every single lookup I store in a variable?

**Comment by Borewit** [comment]
> How do I return a specific value of a key in the result

You cannot create a function that returns a value which is only available after the promise is resolved. You can return a promise, to resolve that value.

JavaScript is non-blocking. That mean, when you call a time consuming operation, like reading a value from MusicBrainz, it will not wait when calling the function,

I see you have this in mind, but this is **not** possible:
```js
  function lookupGender() {
    return mbg.lookupEntity().gender;
  }
```

You can return a promise which, on success, returns the gender of the artist:
```js
function lookupGender() {
  return mbg.lookupEntity().then( artist -> {
      return artist.gender;
   });
}
  
lookupGender().then(gender -> {
  console.log(`Gender of artist is ${gender}`);
});
```

Now pay attention to the sequence
```js
function lookupGender() {
  return mbg.lookupEntity().then( artist -> {
      console.log('2) Only now, much later, we got the aritst');
      return artist.gender;
   });
}
  
lookupGender().then(gender -> {
  console.log('3) And right after 2 the gender');
  console.log(`Gender of artist is ${gender}`);
});
console.log('1) At this moment, we are connecting to MusicBrainz');
```

Using async and await

```js
function async lookupGender() {
  const artist = await mbg.lookupEntity();
  console.log('2) Only now, much later, we got the aritst');
  return artist.gender; // We are still not returning gender directly, still a promise which returns gender
}
  
lookupGender().then(gender -> {
  console.log('3) And right after 2 the gender');
  console.log(`Gender of artist is ${gender}`);
});
console.log('1) At this moment, we are connecting to MusicBrainz');
```

> But how do I do this without changing the successCallback function?

This way you use the functions you had in your original code. But I don't recomand first assigning the callback functions to a variable, but it works as well.
```js
const successCallback= result => {
  console.log(result.gender);
}

const failureCallback= error => {
  console.error(error);
}

mbg.lookupEntity().then(successCallback, failureCallback);
// When we are here, the artist still needs to be resolved

```
