### ISSUE TITLE
TypeError: MusicbrainzApi is not a constructor

### ISSUE THREAD

**Issue by lucacalcaterra** [Borewit/musicbrainz-api#8]
Hi, following your examples on README get this error

const mbApi = new MusicbrainzApi();
              ^

TypeError: MusicbrainzApi is not a constructor

----

why ?

Thanks

**Comment by lucacalcaterra** [comment]
Ok , must be: MusicbrainzApi.MusicBrainzApi instantiating object  (or change import);

**Comment by Havock94** [comment]
@lucacalcaterra thank you, I had the same problem :)

This way it works:

    const musicBrainzApi = require('musicbrainz-api').MusicBrainzApi;
    ....
    var mbApi = new musicBrainzApi({

**Comment by Borewit** [comment]
I completely missed the issue for some reason, I will look into it. 
Thanks for your feedback.
