### ISSUE TITLE
"Only developed for the use in a node.js environment"

### ISSUE THREAD

**Issue by spiff-radio** [Borewit/musicbrainz-api#832]
> Hint
> This package is currently only developed for the use in a [node.js environment](http://nodejs.org/). We are looking into making this package usable in the browser as well.
https://github.com/Borewit/musicbrainz-api#hint

Is this still is the case and is there any plans to make it supported in the browser ?
Thanks !

**Comment by Haschikeks** [comment]
Hi,

yes, its still the case, that it only properly runs in a node environment.
We had plans to support browsers as well, but ran into some technical problems.

But with the the [v0.13.0](https://github.com/Borewit/musicbrainz-api/releases/tag/v0.13.0) release, we might be able to give it another go.
