### ISSUE TITLE
Cover Art Archive API w/ release-group (album)

### ISSUE THREAD

**Issue by Lombardoc4** [Borewit/musicbrainz-api#868]
Currently, `getReleaseCovers` uses the 'release' parameter to find a releases's cover.
Alternatively I'm interested in adding an option to select if the cover is from a
1. Release
2. Release Group

**Ultimately this will be adding support for album images!**

This is the current function
```
public async getReleaseCovers(releaseId: string, coverType?: 'front' | 'back'): Promise<ICoverInfo> {
    const path = ['release', releaseId];
    ...
  }
```

I'd suggest modifying the functions like so:
```
public async getReleaseCovers(releaseId: string, releaseType: 'release' | 'release-group' = 'release', coverType?: 'front' | 'back'): Promise<ICoverInfo> {
      const path = [releaseType, releaseId];
    ...
  }
```

**Comment by Borewit** [comment]
Resolved by #874
