### ISSUE TITLE
Is botAccount optional?

### ISSUE THREAD

**Issue by david-mk-lawrence** [Borewit/musicbrainz-api#872]
Hello 👋 , thank you for this library!

In the readme, the example for getting starting is

```ts
const mbApi = new MusicBrainzApi({
  appName: 'my-app',
  appVersion: '0.1.0',
  appContactInfo: 'user@mail.org',
});
```

however this will not work in Typescript. The `IMusicBrainzConfig` interface currently requires the `botAccount` object (even though the actual username/password is not required). For example adding an empty object for the `botAccount` satisfies Typescript.

```ts
const mbApi = new MusicBrainzApi({
  appName: 'my-app',
  appVersion: '0.1.0',
  appContactInfo: 'user@mail.org',
  // added to satisfy Typescript
  botAccount: {},
});
```

If the botAccount object is actually required then the readme may need a simple update (otherwise maybe the the botAccount object can be made optional)

**Comment by Borewit** [comment]
I believe the `botAccount` is only used when submitting form based data, can probably made optional.
