### ISSUE TITLE
Add ability to turn off rate limiting

### ISSUE THREAD

**Issue by ben-obringer** [Borewit/musicbrainz-api#952]
I'm using my own MusicBrainz server, and it would be nice to turn off rate limiting. Maybe we could add a new field to the config called `disableRateLimiting` and then add some conditional logic to prevent it from running? or maybe we could allow users to set their own values passed into `RateLimitThreshold`. I think the first option makes more sense as it's simpler, and I can't think of reasons why users would want to slow down requests or speed them up (since they'd hit the limit).

**Comment by ben-obringer** [comment]
Also, thank you for creating this library!

**Comment by Borewit** [comment]
Good to hear you appreciate this library.

No problem to add an option disable the rate limiter.

**Comment by ben-obringer** [comment]
Awesome. i'll do that soon

**Comment by ben-obringer** [comment]
Could I get permission to push a branch?
```
git push --set-upstream origin rate-limit-disable
Alias tip: gp --set-upstream origin rate-limit-disable
remote: Permission to Borewit/musicbrainz-api.git denied to ben-obringer.
fatal: unable to access 'https://github.com/Borewit/musicbrainz-api.git/': The requested URL returned error: 403
```

**Comment by Haschikeks** [comment]
Hi,
Thank you for implementing this feature.
You need to fork this repo and create a new branch in your fork. From there you can create a pull request.
