### ISSUE TITLE
`baseUrl` is required field based on typescript definitions

### ISSUE THREAD

**Issue by mjvotaw** [Borewit/musicbrainz-api#977]
This is a super small thing, but wanted to point it out. 

If I copy your initial example into a .ts file, VS Code give me the following error: `Property 'baseUrl' is missing in type '{ appName: string; appVersion: string; appContactInfo: string; }' but required in type 'IMusicBrainzConfig'.`

**Comment by Borewit** [comment]
I made mistake in release [v0.18.1](https://github.com/Borewit/musicbrainz-api/releases/tag/v0.18.1), that does not include the change #976, thanks for pointing that out.

**Comment by Borewit** [comment]
Should be resolved in [v0.18.2](https://github.com/Borewit/musicbrainz-api/releases/tag/v0.18.2)
