### ISSUE TITLE
Question about query

### ISSUE THREAD

**Issue by stuartambient** [Borewit/musicbrainz-api#997]
There is an endpoint mb has for all genres -  `all:  /genre/all?limit=<LIMIT>&offset=<OFFSET>`

I can get the first set (offset 0) by doing - 
`const allGenres = await mbApi.lookup("genre", "all");`

What I can't figure out is how to include the limit and offset in my query.  I've tried, `{limit: n, offset: n}` but no go.
`TypeError: inc.join is not a function`

**Comment by Haschikeks** [comment]
Hi, we currently don't have a implementation that handles the `genre/all` endpoint.
What you can do as a workaround is use the following code to use the query parameters:
```typescript
const genres = await mbApi.restGet("/genre/all",{
    offset:"2"
});
```

Let me know if that works for you.

**Comment by stuartambient** [comment]
@Haschikeks That works, thank you.  I'll have to take a look at source for other functions (i.e. restGet).
